### ISSUE TITLE
[Bug] Mipmap LODs not working correctly in viewer

### ISSUE THREAD

**Issue by Deschamps12** [MeltyPlayer/MeltyTool#49] opened 2024-08-02 16:47 UTC
**Describe the bug**
When trying to export models in any format, it gives missing method error. Also upon importing .BMD the model is black now, previous versions would load materials properly.

System.MissingMethodException: Attempted to access a missing method.
   at fin.model.io.exporters.assimp.indirect.AssimpIndirectModelExporter.ExportFormats(IModelExporterParams modelExporterParams, IReadOnlyList`1 exportedFormats, Boolean exportAllTextures)
   at uni.games.ExporterUtil.Export[T](T threeDFileBundle, Func`1 loaderHandler, ISystemDirectory outputDirectory, IReadOnlyList`1 formats, Boolean overwriteExistingFile, String overrideName) in C:\Users\Ryan\Documents\CSharpWorkspace\FinModelUtility\FinModelUtility\UniversalAssetTool\UniversalAssetTool\src\games\ExporterUtil.cs:line 268
   
   
   On Import
![image](https://github.com/user-attachments/assets/d598df14-938f-422a-bae6-4de008694ac1)

Exporting
![image](https://github.com/user-attachments/assets/df6e5ab9-b0c9-4611-babc-cead710dd5f0)

**Comment by MeltyPlayer** [comment] 2024-08-08 13:38
Thanks for reporting this issue, sorry about that! Exporting is fixed now, though the material issue probably isn't.

Is this model from Twilight Princess?

**Comment by MeltyPlayer** [comment] 2024-08-11 16:28
After more investigation, I've figured out that this problem has to do with how mipmaps are rendered in the viewer. It turns out that the first mipmaps for this character are the expected texture, but the second mipmaps are black (which I'm assuming is expected behavior?). It's always rendering with these second mipmaps for some reason, which is why the character always appears all-black.

So this is just a viewer issue, the characters should still export correctly. I just need to fix how the renderer uses mipmaps, so it switches between textures at the correct distance.

**Comment by MeltyPlayer** [comment] 2024-10-19 01:28
Finally fixed this in a recent commit.

**Closed as completed** 2024-10-19 01:27 UTC
Labels: bug
